version: '2'
services:
  cam:
    restart: always
    environment:
      - DOCKER=True
    build: .
    command: bash docker_entrypoint.sh
    volumes:
      - .:/src
    env_file:
      - .env
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    depends_on:
      - mqtt
  mqtt:
    restart: always
    image: mjenz/rpi-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    env_file:
      - .mqtt_env
volumes:
  source_photos:
