- hosts: all
  tasks:
    - name: Create .env file
      template:
        src: ./templates/env.j2
        dest: ../.env
    - name: Create .env file for MQTT
      template:
        src: ./templates/mqtt_env.j2
        dest: ../.mqtt_env
